# token will allow updating the gh-pages branch of the repository.
secure: "WK1EyUiO76VPcWanCxtBhL7IWTUaCZbzG/x9Xs/TnsL6PaZVdIgxBbEOuUbgwPwFAeKvgah3a2+OFHF7vvFkxZypHSuZqi1yrlZ/l52p07jG4PqzwMiaGwJpqitnfOALucrXOuQnFQ5My5o8ApkXLEgRMG6MSb8LXotSliUVWmQ="

sudo: false
language: java

jdk:
  - oraclejdk8
  - oraclejdk7

cache:
  directories:
    - $HOME/.m2

install: true

script:
  - mvn clean install -DdryRun=true -Dlicense.failOnMissingHeader=true -Dlicense.failOnNotUptodateHeader=true

after_success:
  - ./.utility/deploy.sh
  - ./.utility/gh_pages.sh
  